# use container-based environment
sudo: false

language: python

python:
  - "2.7"

# cache pip and npm package installations
cache:
  pip: true
  directories:
    - node_modules
    - $HOME/.selenium/

# limit the depth of the commits we clone
git:
  depth: 5

addons:
  firefox: "44.0"

env:
  global:
    - ISSUES_REPO_URI=webcompat/webcompat-tests/issues
    - FAKE_ID=e80a666fbf1fa9ea18db
    - FAKE_SECRET=688c4546f09624f8c44773b22268064dfca19a59

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mkdir -p $HOME/.selenium && cd $HOME/.selenium && wget -nc http://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar"
  - java -jar selenium-server-standalone-2.52.0.jar &> /dev/null &
  - cd -

install:
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install
  - travis_retry pip install -r requirements.txt 
  - cp config/secrets.py.example config/secrets.py
  # lint python
  - pep8 --ignore=E402 webcompat/ tests/ config/secrets.py.example
  - git submodule init && git submodule update
  - python run.py -t &

before_script:
  - "sleep 2"
  # lint JS in default eslint task
  - grunt

# now run the tests!
# if this is a pull request from a fork, TRAVIS_SECURE_ENV_VARS will be false, so
# just run the non-auth tests. otherwise, run everything.
script:
  - nosetests
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "false" ] ; then node_modules/.bin/intern-runner reporters=console config=tests/intern functionalSuites=tests/functional-nonauth ; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] ; then node_modules/.bin/intern-runner reporters=console config=tests/intern user="$USER" pw="$PW" ; fi
